/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUmsatzRouteImport } from './routes/_authenticated/umsatz'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedKalenderRouteImport } from './routes/_authenticated/kalender'
import { Route as AuthenticatedImporteRouteImport } from './routes/_authenticated/importe'
import { Route as AuthenticatedFotosRouteImport } from './routes/_authenticated/fotos'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedDokumenteRouteImport } from './routes/_authenticated/dokumente'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBezahltRouteImport } from './routes/_authenticated/bezahlt'
import { Route as AuthenticatedArchivRouteImport } from './routes/_authenticated/archiv'
import { Route as AuthenticatedAktivitaetRouteImport } from './routes/_authenticated/aktivitaet'
import { Route as AuthenticatedAbrechnungRouteImport } from './routes/_authenticated/abrechnung'
import { Route as AuthenticatedProjekteIndexRouteImport } from './routes/_authenticated/projekte.index'
import { Route as AuthenticatedMitarbeiterIndexRouteImport } from './routes/_authenticated/mitarbeiter.index'
import { Route as AuthenticatedMeineArbeitIndexRouteImport } from './routes/_authenticated/meine-arbeit.index'
import { Route as AuthenticatedKundenIndexRouteImport } from './routes/_authenticated/kunden.index'
import { Route as AuthenticatedEinstellungenIndexRouteImport } from './routes/_authenticated/einstellungen.index'
import { Route as AuthenticatedAuftraegeIndexRouteImport } from './routes/_authenticated/auftraege.index'
import { Route as AuthenticatedProjekteIdRouteImport } from './routes/_authenticated/projekte.$id'
import { Route as AuthenticatedMitarbeiterIdRouteImport } from './routes/_authenticated/mitarbeiter.$id'
import { Route as AuthenticatedMeineArbeitIdRouteImport } from './routes/_authenticated/meine-arbeit.$id'
import { Route as AuthenticatedKundenIdRouteImport } from './routes/_authenticated/kunden.$id'
import { Route as AuthenticatedEinstellungenSystemRouteImport } from './routes/_authenticated/einstellungen.system'
import { Route as AuthenticatedEinstellungenStatusRouteImport } from './routes/_authenticated/einstellungen.status'
import { Route as AuthenticatedEinstellungenSicherheitRouteImport } from './routes/_authenticated/einstellungen.sicherheit'
import { Route as AuthenticatedEinstellungenSeitenRouteImport } from './routes/_authenticated/einstellungen.seiten'
import { Route as AuthenticatedEinstellungenRollenRouteImport } from './routes/_authenticated/einstellungen.rollen'
import { Route as AuthenticatedEinstellungenMobileRouteImport } from './routes/_authenticated/einstellungen.mobile'
import { Route as AuthenticatedEinstellungenLeistungenRouteImport } from './routes/_authenticated/einstellungen.leistungen'
import { Route as AuthenticatedEinstellungenFirmenprofilRouteImport } from './routes/_authenticated/einstellungen.firmenprofil'
import { Route as AuthenticatedEinstellungenFelderRouteImport } from './routes/_authenticated/einstellungen.felder'
import { Route as AuthenticatedEinstellungenBenutzerRouteImport } from './routes/_authenticated/einstellungen.benutzer'
import { Route as AuthenticatedEinstellungenAktivitaetRouteImport } from './routes/_authenticated/einstellungen.aktivitaet'
import { Route as AuthenticatedAuftraegeIdRouteImport } from './routes/_authenticated/auftraege.$id'
import { Route as AuthenticatedAbrechnungIdRouteImport } from './routes/_authenticated/abrechnung.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUmsatzRoute = AuthenticatedUmsatzRouteImport.update({
  id: '/umsatz',
  path: '/umsatz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKalenderRoute = AuthenticatedKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImporteRoute = AuthenticatedImporteRouteImport.update({
  id: '/importe',
  path: '/importe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFotosRoute = AuthenticatedFotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDokumenteRoute = AuthenticatedDokumenteRouteImport.update({
  id: '/dokumente',
  path: '/dokumente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBezahltRoute = AuthenticatedBezahltRouteImport.update({
  id: '/bezahlt',
  path: '/bezahlt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchivRoute = AuthenticatedArchivRouteImport.update({
  id: '/archiv',
  path: '/archiv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAktivitaetRoute = AuthenticatedAktivitaetRouteImport.update({
  id: '/aktivitaet',
  path: '/aktivitaet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbrechnungRoute = AuthenticatedAbrechnungRouteImport.update({
  id: '/abrechnung',
  path: '/abrechnung',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjekteIndexRoute =
  AuthenticatedProjekteIndexRouteImport.update({
    id: '/projekte/',
    path: '/projekte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMitarbeiterIndexRoute =
  AuthenticatedMitarbeiterIndexRouteImport.update({
    id: '/mitarbeiter/',
    path: '/mitarbeiter/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeineArbeitIndexRoute =
  AuthenticatedMeineArbeitIndexRouteImport.update({
    id: '/meine-arbeit/',
    path: '/meine-arbeit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKundenIndexRoute =
  AuthenticatedKundenIndexRouteImport.update({
    id: '/kunden/',
    path: '/kunden/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEinstellungenIndexRoute =
  AuthenticatedEinstellungenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedAuftraegeIndexRoute =
  AuthenticatedAuftraegeIndexRouteImport.update({
    id: '/auftraege/',
    path: '/auftraege/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjekteIdRoute = AuthenticatedProjekteIdRouteImport.update({
  id: '/projekte/$id',
  path: '/projekte/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMitarbeiterIdRoute =
  AuthenticatedMitarbeiterIdRouteImport.update({
    id: '/mitarbeiter/$id',
    path: '/mitarbeiter/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeineArbeitIdRoute =
  AuthenticatedMeineArbeitIdRouteImport.update({
    id: '/meine-arbeit/$id',
    path: '/meine-arbeit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKundenIdRoute = AuthenticatedKundenIdRouteImport.update({
  id: '/kunden/$id',
  path: '/kunden/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenSystemRoute =
  AuthenticatedEinstellungenSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedEinstellungenStatusRoute =
  AuthenticatedEinstellungenStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedEinstellungenSicherheitRoute =
  AuthenticatedEinstellungenSicherheitRouteImport.update({
    id: '/sicherheit',
    path: '/sicherheit',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedEinstellungenSeitenRoute =
  AuthenticatedEinstellungenSeitenRouteImport.update({
    id: '/seiten',
    path: '/seiten',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedEinstellungenRollenRoute =
  AuthenticatedEinstellungenRollenRouteImport.update({
    id: '/rollen',
    path: '/rollen',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedEinstellungenMobileRoute =
  AuthenticatedEinstellungenMobileRouteImport.update({
    id: '/mobile',
    path: '/mobile',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedEinstellungenLeistungenRoute =
  AuthenticatedEinstellungenLeistungenRouteImport.update({
    id: '/leistungen',
    path: '/leistungen',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedEinstellungenFirmenprofilRoute =
  AuthenticatedEinstellungenFirmenprofilRouteImport.update({
    id: '/firmenprofil',
    path: '/firmenprofil',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedEinstellungenFelderRoute =
  AuthenticatedEinstellungenFelderRouteImport.update({
    id: '/felder',
    path: '/felder',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedEinstellungenBenutzerRoute =
  AuthenticatedEinstellungenBenutzerRouteImport.update({
    id: '/benutzer',
    path: '/benutzer',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedEinstellungenAktivitaetRoute =
  AuthenticatedEinstellungenAktivitaetRouteImport.update({
    id: '/aktivitaet',
    path: '/aktivitaet',
    getParentRoute: () => AuthenticatedEinstellungenRoute,
  } as any)
const AuthenticatedAuftraegeIdRoute =
  AuthenticatedAuftraegeIdRouteImport.update({
    id: '/auftraege/$id',
    path: '/auftraege/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAbrechnungIdRoute =
  AuthenticatedAbrechnungIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAbrechnungRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/abrechnung': typeof AuthenticatedAbrechnungRouteWithChildren
  '/aktivitaet': typeof AuthenticatedAktivitaetRoute
  '/archiv': typeof AuthenticatedArchivRoute
  '/bezahlt': typeof AuthenticatedBezahltRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dokumente': typeof AuthenticatedDokumenteRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRouteWithChildren
  '/fotos': typeof AuthenticatedFotosRoute
  '/importe': typeof AuthenticatedImporteRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/umsatz': typeof AuthenticatedUmsatzRoute
  '/abrechnung/$id': typeof AuthenticatedAbrechnungIdRoute
  '/auftraege/$id': typeof AuthenticatedAuftraegeIdRoute
  '/einstellungen/aktivitaet': typeof AuthenticatedEinstellungenAktivitaetRoute
  '/einstellungen/benutzer': typeof AuthenticatedEinstellungenBenutzerRoute
  '/einstellungen/felder': typeof AuthenticatedEinstellungenFelderRoute
  '/einstellungen/firmenprofil': typeof AuthenticatedEinstellungenFirmenprofilRoute
  '/einstellungen/leistungen': typeof AuthenticatedEinstellungenLeistungenRoute
  '/einstellungen/mobile': typeof AuthenticatedEinstellungenMobileRoute
  '/einstellungen/rollen': typeof AuthenticatedEinstellungenRollenRoute
  '/einstellungen/seiten': typeof AuthenticatedEinstellungenSeitenRoute
  '/einstellungen/sicherheit': typeof AuthenticatedEinstellungenSicherheitRoute
  '/einstellungen/status': typeof AuthenticatedEinstellungenStatusRoute
  '/einstellungen/system': typeof AuthenticatedEinstellungenSystemRoute
  '/kunden/$id': typeof AuthenticatedKundenIdRoute
  '/meine-arbeit/$id': typeof AuthenticatedMeineArbeitIdRoute
  '/mitarbeiter/$id': typeof AuthenticatedMitarbeiterIdRoute
  '/projekte/$id': typeof AuthenticatedProjekteIdRoute
  '/auftraege/': typeof AuthenticatedAuftraegeIndexRoute
  '/einstellungen/': typeof AuthenticatedEinstellungenIndexRoute
  '/kunden/': typeof AuthenticatedKundenIndexRoute
  '/meine-arbeit/': typeof AuthenticatedMeineArbeitIndexRoute
  '/mitarbeiter/': typeof AuthenticatedMitarbeiterIndexRoute
  '/projekte/': typeof AuthenticatedProjekteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/abrechnung': typeof AuthenticatedAbrechnungRouteWithChildren
  '/aktivitaet': typeof AuthenticatedAktivitaetRoute
  '/archiv': typeof AuthenticatedArchivRoute
  '/bezahlt': typeof AuthenticatedBezahltRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dokumente': typeof AuthenticatedDokumenteRoute
  '/fotos': typeof AuthenticatedFotosRoute
  '/importe': typeof AuthenticatedImporteRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/umsatz': typeof AuthenticatedUmsatzRoute
  '/abrechnung/$id': typeof AuthenticatedAbrechnungIdRoute
  '/auftraege/$id': typeof AuthenticatedAuftraegeIdRoute
  '/einstellungen/aktivitaet': typeof AuthenticatedEinstellungenAktivitaetRoute
  '/einstellungen/benutzer': typeof AuthenticatedEinstellungenBenutzerRoute
  '/einstellungen/felder': typeof AuthenticatedEinstellungenFelderRoute
  '/einstellungen/firmenprofil': typeof AuthenticatedEinstellungenFirmenprofilRoute
  '/einstellungen/leistungen': typeof AuthenticatedEinstellungenLeistungenRoute
  '/einstellungen/mobile': typeof AuthenticatedEinstellungenMobileRoute
  '/einstellungen/rollen': typeof AuthenticatedEinstellungenRollenRoute
  '/einstellungen/seiten': typeof AuthenticatedEinstellungenSeitenRoute
  '/einstellungen/sicherheit': typeof AuthenticatedEinstellungenSicherheitRoute
  '/einstellungen/status': typeof AuthenticatedEinstellungenStatusRoute
  '/einstellungen/system': typeof AuthenticatedEinstellungenSystemRoute
  '/kunden/$id': typeof AuthenticatedKundenIdRoute
  '/meine-arbeit/$id': typeof AuthenticatedMeineArbeitIdRoute
  '/mitarbeiter/$id': typeof AuthenticatedMitarbeiterIdRoute
  '/projekte/$id': typeof AuthenticatedProjekteIdRoute
  '/auftraege': typeof AuthenticatedAuftraegeIndexRoute
  '/einstellungen': typeof AuthenticatedEinstellungenIndexRoute
  '/kunden': typeof AuthenticatedKundenIndexRoute
  '/meine-arbeit': typeof AuthenticatedMeineArbeitIndexRoute
  '/mitarbeiter': typeof AuthenticatedMitarbeiterIndexRoute
  '/projekte': typeof AuthenticatedProjekteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/_authenticated/abrechnung': typeof AuthenticatedAbrechnungRouteWithChildren
  '/_authenticated/aktivitaet': typeof AuthenticatedAktivitaetRoute
  '/_authenticated/archiv': typeof AuthenticatedArchivRoute
  '/_authenticated/bezahlt': typeof AuthenticatedBezahltRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dokumente': typeof AuthenticatedDokumenteRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRouteWithChildren
  '/_authenticated/fotos': typeof AuthenticatedFotosRoute
  '/_authenticated/importe': typeof AuthenticatedImporteRoute
  '/_authenticated/kalender': typeof AuthenticatedKalenderRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/umsatz': typeof AuthenticatedUmsatzRoute
  '/_authenticated/abrechnung/$id': typeof AuthenticatedAbrechnungIdRoute
  '/_authenticated/auftraege/$id': typeof AuthenticatedAuftraegeIdRoute
  '/_authenticated/einstellungen/aktivitaet': typeof AuthenticatedEinstellungenAktivitaetRoute
  '/_authenticated/einstellungen/benutzer': typeof AuthenticatedEinstellungenBenutzerRoute
  '/_authenticated/einstellungen/felder': typeof AuthenticatedEinstellungenFelderRoute
  '/_authenticated/einstellungen/firmenprofil': typeof AuthenticatedEinstellungenFirmenprofilRoute
  '/_authenticated/einstellungen/leistungen': typeof AuthenticatedEinstellungenLeistungenRoute
  '/_authenticated/einstellungen/mobile': typeof AuthenticatedEinstellungenMobileRoute
  '/_authenticated/einstellungen/rollen': typeof AuthenticatedEinstellungenRollenRoute
  '/_authenticated/einstellungen/seiten': typeof AuthenticatedEinstellungenSeitenRoute
  '/_authenticated/einstellungen/sicherheit': typeof AuthenticatedEinstellungenSicherheitRoute
  '/_authenticated/einstellungen/status': typeof AuthenticatedEinstellungenStatusRoute
  '/_authenticated/einstellungen/system': typeof AuthenticatedEinstellungenSystemRoute
  '/_authenticated/kunden/$id': typeof AuthenticatedKundenIdRoute
  '/_authenticated/meine-arbeit/$id': typeof AuthenticatedMeineArbeitIdRoute
  '/_authenticated/mitarbeiter/$id': typeof AuthenticatedMitarbeiterIdRoute
  '/_authenticated/projekte/$id': typeof AuthenticatedProjekteIdRoute
  '/_authenticated/auftraege/': typeof AuthenticatedAuftraegeIndexRoute
  '/_authenticated/einstellungen/': typeof AuthenticatedEinstellungenIndexRoute
  '/_authenticated/kunden/': typeof AuthenticatedKundenIndexRoute
  '/_authenticated/meine-arbeit/': typeof AuthenticatedMeineArbeitIndexRoute
  '/_authenticated/mitarbeiter/': typeof AuthenticatedMitarbeiterIndexRoute
  '/_authenticated/projekte/': typeof AuthenticatedProjekteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/abrechnung'
    | '/aktivitaet'
    | '/archiv'
    | '/bezahlt'
    | '/dashboard'
    | '/dokumente'
    | '/einstellungen'
    | '/fotos'
    | '/importe'
    | '/kalender'
    | '/profil'
    | '/umsatz'
    | '/abrechnung/$id'
    | '/auftraege/$id'
    | '/einstellungen/aktivitaet'
    | '/einstellungen/benutzer'
    | '/einstellungen/felder'
    | '/einstellungen/firmenprofil'
    | '/einstellungen/leistungen'
    | '/einstellungen/mobile'
    | '/einstellungen/rollen'
    | '/einstellungen/seiten'
    | '/einstellungen/sicherheit'
    | '/einstellungen/status'
    | '/einstellungen/system'
    | '/kunden/$id'
    | '/meine-arbeit/$id'
    | '/mitarbeiter/$id'
    | '/projekte/$id'
    | '/auftraege/'
    | '/einstellungen/'
    | '/kunden/'
    | '/meine-arbeit/'
    | '/mitarbeiter/'
    | '/projekte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/abrechnung'
    | '/aktivitaet'
    | '/archiv'
    | '/bezahlt'
    | '/dashboard'
    | '/dokumente'
    | '/fotos'
    | '/importe'
    | '/kalender'
    | '/profil'
    | '/umsatz'
    | '/abrechnung/$id'
    | '/auftraege/$id'
    | '/einstellungen/aktivitaet'
    | '/einstellungen/benutzer'
    | '/einstellungen/felder'
    | '/einstellungen/firmenprofil'
    | '/einstellungen/leistungen'
    | '/einstellungen/mobile'
    | '/einstellungen/rollen'
    | '/einstellungen/seiten'
    | '/einstellungen/sicherheit'
    | '/einstellungen/status'
    | '/einstellungen/system'
    | '/kunden/$id'
    | '/meine-arbeit/$id'
    | '/mitarbeiter/$id'
    | '/projekte/$id'
    | '/auftraege'
    | '/einstellungen'
    | '/kunden'
    | '/meine-arbeit'
    | '/mitarbeiter'
    | '/projekte'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/_authenticated/abrechnung'
    | '/_authenticated/aktivitaet'
    | '/_authenticated/archiv'
    | '/_authenticated/bezahlt'
    | '/_authenticated/dashboard'
    | '/_authenticated/dokumente'
    | '/_authenticated/einstellungen'
    | '/_authenticated/fotos'
    | '/_authenticated/importe'
    | '/_authenticated/kalender'
    | '/_authenticated/profil'
    | '/_authenticated/umsatz'
    | '/_authenticated/abrechnung/$id'
    | '/_authenticated/auftraege/$id'
    | '/_authenticated/einstellungen/aktivitaet'
    | '/_authenticated/einstellungen/benutzer'
    | '/_authenticated/einstellungen/felder'
    | '/_authenticated/einstellungen/firmenprofil'
    | '/_authenticated/einstellungen/leistungen'
    | '/_authenticated/einstellungen/mobile'
    | '/_authenticated/einstellungen/rollen'
    | '/_authenticated/einstellungen/seiten'
    | '/_authenticated/einstellungen/sicherheit'
    | '/_authenticated/einstellungen/status'
    | '/_authenticated/einstellungen/system'
    | '/_authenticated/kunden/$id'
    | '/_authenticated/meine-arbeit/$id'
    | '/_authenticated/mitarbeiter/$id'
    | '/_authenticated/projekte/$id'
    | '/_authenticated/auftraege/'
    | '/_authenticated/einstellungen/'
    | '/_authenticated/kunden/'
    | '/_authenticated/meine-arbeit/'
    | '/_authenticated/mitarbeiter/'
    | '/_authenticated/projekte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/umsatz': {
      id: '/_authenticated/umsatz'
      path: '/umsatz'
      fullPath: '/umsatz'
      preLoaderRoute: typeof AuthenticatedUmsatzRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalender': {
      id: '/_authenticated/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AuthenticatedKalenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importe': {
      id: '/_authenticated/importe'
      path: '/importe'
      fullPath: '/importe'
      preLoaderRoute: typeof AuthenticatedImporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fotos': {
      id: '/_authenticated/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof AuthenticatedFotosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dokumente': {
      id: '/_authenticated/dokumente'
      path: '/dokumente'
      fullPath: '/dokumente'
      preLoaderRoute: typeof AuthenticatedDokumenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bezahlt': {
      id: '/_authenticated/bezahlt'
      path: '/bezahlt'
      fullPath: '/bezahlt'
      preLoaderRoute: typeof AuthenticatedBezahltRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archiv': {
      id: '/_authenticated/archiv'
      path: '/archiv'
      fullPath: '/archiv'
      preLoaderRoute: typeof AuthenticatedArchivRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aktivitaet': {
      id: '/_authenticated/aktivitaet'
      path: '/aktivitaet'
      fullPath: '/aktivitaet'
      preLoaderRoute: typeof AuthenticatedAktivitaetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abrechnung': {
      id: '/_authenticated/abrechnung'
      path: '/abrechnung'
      fullPath: '/abrechnung'
      preLoaderRoute: typeof AuthenticatedAbrechnungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte/': {
      id: '/_authenticated/projekte/'
      path: '/projekte'
      fullPath: '/projekte/'
      preLoaderRoute: typeof AuthenticatedProjekteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mitarbeiter/': {
      id: '/_authenticated/mitarbeiter/'
      path: '/mitarbeiter'
      fullPath: '/mitarbeiter/'
      preLoaderRoute: typeof AuthenticatedMitarbeiterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meine-arbeit/': {
      id: '/_authenticated/meine-arbeit/'
      path: '/meine-arbeit'
      fullPath: '/meine-arbeit/'
      preLoaderRoute: typeof AuthenticatedMeineArbeitIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunden/': {
      id: '/_authenticated/kunden/'
      path: '/kunden'
      fullPath: '/kunden/'
      preLoaderRoute: typeof AuthenticatedKundenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen/': {
      id: '/_authenticated/einstellungen/'
      path: '/'
      fullPath: '/einstellungen/'
      preLoaderRoute: typeof AuthenticatedEinstellungenIndexRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/auftraege/': {
      id: '/_authenticated/auftraege/'
      path: '/auftraege'
      fullPath: '/auftraege/'
      preLoaderRoute: typeof AuthenticatedAuftraegeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte/$id': {
      id: '/_authenticated/projekte/$id'
      path: '/projekte/$id'
      fullPath: '/projekte/$id'
      preLoaderRoute: typeof AuthenticatedProjekteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mitarbeiter/$id': {
      id: '/_authenticated/mitarbeiter/$id'
      path: '/mitarbeiter/$id'
      fullPath: '/mitarbeiter/$id'
      preLoaderRoute: typeof AuthenticatedMitarbeiterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meine-arbeit/$id': {
      id: '/_authenticated/meine-arbeit/$id'
      path: '/meine-arbeit/$id'
      fullPath: '/meine-arbeit/$id'
      preLoaderRoute: typeof AuthenticatedMeineArbeitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunden/$id': {
      id: '/_authenticated/kunden/$id'
      path: '/kunden/$id'
      fullPath: '/kunden/$id'
      preLoaderRoute: typeof AuthenticatedKundenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen/system': {
      id: '/_authenticated/einstellungen/system'
      path: '/system'
      fullPath: '/einstellungen/system'
      preLoaderRoute: typeof AuthenticatedEinstellungenSystemRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/einstellungen/status': {
      id: '/_authenticated/einstellungen/status'
      path: '/status'
      fullPath: '/einstellungen/status'
      preLoaderRoute: typeof AuthenticatedEinstellungenStatusRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/einstellungen/sicherheit': {
      id: '/_authenticated/einstellungen/sicherheit'
      path: '/sicherheit'
      fullPath: '/einstellungen/sicherheit'
      preLoaderRoute: typeof AuthenticatedEinstellungenSicherheitRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/einstellungen/seiten': {
      id: '/_authenticated/einstellungen/seiten'
      path: '/seiten'
      fullPath: '/einstellungen/seiten'
      preLoaderRoute: typeof AuthenticatedEinstellungenSeitenRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/einstellungen/rollen': {
      id: '/_authenticated/einstellungen/rollen'
      path: '/rollen'
      fullPath: '/einstellungen/rollen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRollenRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/einstellungen/mobile': {
      id: '/_authenticated/einstellungen/mobile'
      path: '/mobile'
      fullPath: '/einstellungen/mobile'
      preLoaderRoute: typeof AuthenticatedEinstellungenMobileRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/einstellungen/leistungen': {
      id: '/_authenticated/einstellungen/leistungen'
      path: '/leistungen'
      fullPath: '/einstellungen/leistungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenLeistungenRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/einstellungen/firmenprofil': {
      id: '/_authenticated/einstellungen/firmenprofil'
      path: '/firmenprofil'
      fullPath: '/einstellungen/firmenprofil'
      preLoaderRoute: typeof AuthenticatedEinstellungenFirmenprofilRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/einstellungen/felder': {
      id: '/_authenticated/einstellungen/felder'
      path: '/felder'
      fullPath: '/einstellungen/felder'
      preLoaderRoute: typeof AuthenticatedEinstellungenFelderRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/einstellungen/benutzer': {
      id: '/_authenticated/einstellungen/benutzer'
      path: '/benutzer'
      fullPath: '/einstellungen/benutzer'
      preLoaderRoute: typeof AuthenticatedEinstellungenBenutzerRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/einstellungen/aktivitaet': {
      id: '/_authenticated/einstellungen/aktivitaet'
      path: '/aktivitaet'
      fullPath: '/einstellungen/aktivitaet'
      preLoaderRoute: typeof AuthenticatedEinstellungenAktivitaetRouteImport
      parentRoute: typeof AuthenticatedEinstellungenRoute
    }
    '/_authenticated/auftraege/$id': {
      id: '/_authenticated/auftraege/$id'
      path: '/auftraege/$id'
      fullPath: '/auftraege/$id'
      preLoaderRoute: typeof AuthenticatedAuftraegeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abrechnung/$id': {
      id: '/_authenticated/abrechnung/$id'
      path: '/$id'
      fullPath: '/abrechnung/$id'
      preLoaderRoute: typeof AuthenticatedAbrechnungIdRouteImport
      parentRoute: typeof AuthenticatedAbrechnungRoute
    }
  }
}

interface AuthenticatedAbrechnungRouteChildren {
  AuthenticatedAbrechnungIdRoute: typeof AuthenticatedAbrechnungIdRoute
}

const AuthenticatedAbrechnungRouteChildren: AuthenticatedAbrechnungRouteChildren =
  {
    AuthenticatedAbrechnungIdRoute: AuthenticatedAbrechnungIdRoute,
  }

const AuthenticatedAbrechnungRouteWithChildren =
  AuthenticatedAbrechnungRoute._addFileChildren(
    AuthenticatedAbrechnungRouteChildren,
  )

interface AuthenticatedEinstellungenRouteChildren {
  AuthenticatedEinstellungenAktivitaetRoute: typeof AuthenticatedEinstellungenAktivitaetRoute
  AuthenticatedEinstellungenBenutzerRoute: typeof AuthenticatedEinstellungenBenutzerRoute
  AuthenticatedEinstellungenFelderRoute: typeof AuthenticatedEinstellungenFelderRoute
  AuthenticatedEinstellungenFirmenprofilRoute: typeof AuthenticatedEinstellungenFirmenprofilRoute
  AuthenticatedEinstellungenLeistungenRoute: typeof AuthenticatedEinstellungenLeistungenRoute
  AuthenticatedEinstellungenMobileRoute: typeof AuthenticatedEinstellungenMobileRoute
  AuthenticatedEinstellungenRollenRoute: typeof AuthenticatedEinstellungenRollenRoute
  AuthenticatedEinstellungenSeitenRoute: typeof AuthenticatedEinstellungenSeitenRoute
  AuthenticatedEinstellungenSicherheitRoute: typeof AuthenticatedEinstellungenSicherheitRoute
  AuthenticatedEinstellungenStatusRoute: typeof AuthenticatedEinstellungenStatusRoute
  AuthenticatedEinstellungenSystemRoute: typeof AuthenticatedEinstellungenSystemRoute
  AuthenticatedEinstellungenIndexRoute: typeof AuthenticatedEinstellungenIndexRoute
}

const AuthenticatedEinstellungenRouteChildren: AuthenticatedEinstellungenRouteChildren =
  {
    AuthenticatedEinstellungenAktivitaetRoute:
      AuthenticatedEinstellungenAktivitaetRoute,
    AuthenticatedEinstellungenBenutzerRoute:
      AuthenticatedEinstellungenBenutzerRoute,
    AuthenticatedEinstellungenFelderRoute:
      AuthenticatedEinstellungenFelderRoute,
    AuthenticatedEinstellungenFirmenprofilRoute:
      AuthenticatedEinstellungenFirmenprofilRoute,
    AuthenticatedEinstellungenLeistungenRoute:
      AuthenticatedEinstellungenLeistungenRoute,
    AuthenticatedEinstellungenMobileRoute:
      AuthenticatedEinstellungenMobileRoute,
    AuthenticatedEinstellungenRollenRoute:
      AuthenticatedEinstellungenRollenRoute,
    AuthenticatedEinstellungenSeitenRoute:
      AuthenticatedEinstellungenSeitenRoute,
    AuthenticatedEinstellungenSicherheitRoute:
      AuthenticatedEinstellungenSicherheitRoute,
    AuthenticatedEinstellungenStatusRoute:
      AuthenticatedEinstellungenStatusRoute,
    AuthenticatedEinstellungenSystemRoute:
      AuthenticatedEinstellungenSystemRoute,
    AuthenticatedEinstellungenIndexRoute: AuthenticatedEinstellungenIndexRoute,
  }

const AuthenticatedEinstellungenRouteWithChildren =
  AuthenticatedEinstellungenRoute._addFileChildren(
    AuthenticatedEinstellungenRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbrechnungRoute: typeof AuthenticatedAbrechnungRouteWithChildren
  AuthenticatedAktivitaetRoute: typeof AuthenticatedAktivitaetRoute
  AuthenticatedArchivRoute: typeof AuthenticatedArchivRoute
  AuthenticatedBezahltRoute: typeof AuthenticatedBezahltRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDokumenteRoute: typeof AuthenticatedDokumenteRoute
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRouteWithChildren
  AuthenticatedFotosRoute: typeof AuthenticatedFotosRoute
  AuthenticatedImporteRoute: typeof AuthenticatedImporteRoute
  AuthenticatedKalenderRoute: typeof AuthenticatedKalenderRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedUmsatzRoute: typeof AuthenticatedUmsatzRoute
  AuthenticatedAuftraegeIdRoute: typeof AuthenticatedAuftraegeIdRoute
  AuthenticatedKundenIdRoute: typeof AuthenticatedKundenIdRoute
  AuthenticatedMeineArbeitIdRoute: typeof AuthenticatedMeineArbeitIdRoute
  AuthenticatedMitarbeiterIdRoute: typeof AuthenticatedMitarbeiterIdRoute
  AuthenticatedProjekteIdRoute: typeof AuthenticatedProjekteIdRoute
  AuthenticatedAuftraegeIndexRoute: typeof AuthenticatedAuftraegeIndexRoute
  AuthenticatedKundenIndexRoute: typeof AuthenticatedKundenIndexRoute
  AuthenticatedMeineArbeitIndexRoute: typeof AuthenticatedMeineArbeitIndexRoute
  AuthenticatedMitarbeiterIndexRoute: typeof AuthenticatedMitarbeiterIndexRoute
  AuthenticatedProjekteIndexRoute: typeof AuthenticatedProjekteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbrechnungRoute: AuthenticatedAbrechnungRouteWithChildren,
  AuthenticatedAktivitaetRoute: AuthenticatedAktivitaetRoute,
  AuthenticatedArchivRoute: AuthenticatedArchivRoute,
  AuthenticatedBezahltRoute: AuthenticatedBezahltRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDokumenteRoute: AuthenticatedDokumenteRoute,
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRouteWithChildren,
  AuthenticatedFotosRoute: AuthenticatedFotosRoute,
  AuthenticatedImporteRoute: AuthenticatedImporteRoute,
  AuthenticatedKalenderRoute: AuthenticatedKalenderRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedUmsatzRoute: AuthenticatedUmsatzRoute,
  AuthenticatedAuftraegeIdRoute: AuthenticatedAuftraegeIdRoute,
  AuthenticatedKundenIdRoute: AuthenticatedKundenIdRoute,
  AuthenticatedMeineArbeitIdRoute: AuthenticatedMeineArbeitIdRoute,
  AuthenticatedMitarbeiterIdRoute: AuthenticatedMitarbeiterIdRoute,
  AuthenticatedProjekteIdRoute: AuthenticatedProjekteIdRoute,
  AuthenticatedAuftraegeIndexRoute: AuthenticatedAuftraegeIndexRoute,
  AuthenticatedKundenIndexRoute: AuthenticatedKundenIndexRoute,
  AuthenticatedMeineArbeitIndexRoute: AuthenticatedMeineArbeitIndexRoute,
  AuthenticatedMitarbeiterIndexRoute: AuthenticatedMitarbeiterIndexRoute,
  AuthenticatedProjekteIndexRoute: AuthenticatedProjekteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
